// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.customers", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Customer_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("API.Models.items", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Item_Price")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("items");
                });

            modelBuilder.Entity("API.Models.orders", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Customer_Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomersID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CustomersID");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("API.Models.orders_item", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Item_Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("Order_Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("itemsID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ordersID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("itemsID");

                    b.HasIndex("ordersID");

                    b.ToTable("orders_Items");
                });

            modelBuilder.Entity("API.Models.orders", b =>
                {
                    b.HasOne("API.Models.customers", "Customers")
                        .WithMany()
                        .HasForeignKey("CustomersID");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("API.Models.orders_item", b =>
                {
                    b.HasOne("API.Models.items", null)
                        .WithMany("Orders_Items")
                        .HasForeignKey("itemsID");

                    b.HasOne("API.Models.orders", null)
                        .WithMany("Orders_Items")
                        .HasForeignKey("ordersID");
                });

            modelBuilder.Entity("API.Models.items", b =>
                {
                    b.Navigation("Orders_Items");
                });

            modelBuilder.Entity("API.Models.orders", b =>
                {
                    b.Navigation("Orders_Items");
                });
#pragma warning restore 612, 618
        }
    }
}
